version = "0.1.0"
author = "Dagger Contracts Authors"
description = "Nim API for the Dagger smart contracts"
license = "MIT"

requires "web3"
requires "stint"
requires "byteutils"
requires "nimcrypto"
requires "chronos"
requires "asynctest >= 0.3.0 & < 0.4.0"
requires "https://github.com/status-im/nim-contract-abi >= 0.2.0 & < 0.3.0"
