version = "0.1.0"
author = "Dagger Contracts Authors"
description = "Nim API for the Dagger smart contracts"
license = "MIT"

requires "https://github.com/status-im/nim-ethers >= 0.1.0 & < 0.2.0"
requires "stint"
requires "byteutils"
requires "nimcrypto"
requires "chronos"
requires "asynctest >= 0.3.0 & < 0.4.0"
requires "contractabi >= 0.4.0 & < 0.5.0"
